### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by TomatoSeal** [PiggyAwesome/discord-token-onliner-py#2]
After trying to fix a bit of your code, still not working, you might need to put more effort into this code.

The test is not working.

**Comment by TomatoSeal** [comment]
Error after open main.py is:
    self.required_action = resp['d']['required_action']
KeyError: 'required_action'

**Comment by TomatoSeal** [comment]
fixed the issue the code works.

Modify this part of the authenticate method:

self.required_action = resp['d']['required_action']
Into:
self.required_action = resp['d'].get('required_action', None)

**Comment by TomatoSeal** [comment]
If the tokens are flagged can't be authenticated online, but still a good program.

**Comment by PiggyAwesome** [comment]
> If the tokens are flagged can't be authenticated online, but still a good program.

Thank you for your help and debugging!
